plugins {
    id 'fabric-loom' version '1.14-SNAPSHOT'
    id 'java'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    mavenCentral()
    maven { url = 'https://maven.fabricmc.net/' }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
    // JNA для тёмного тулбара Windows (DwmSetWindowAttribute), только Windows.
    modImplementation 'net.java.dev.jna:jna:5.15.0'

    // JCodec для чистокровного декодирования MP4-видеофонов в майнкрафте без потери качества
    implementation 'org.jcodec:jcodec:0.2.5'
    implementation 'org.jcodec:jcodec-javase:0.2.5'

    compileOnly 'org.projectlombok:lombok:1.18.36'
    annotationProcessor 'org.projectlombok:lombok:1.18.36'
    compileOnly files('libs/lumen-shaded-dependencies.jar')
    compileOnly fileTree(dir: 'runtime-resources/META-INF/jars', include: ['*.jar'])
}

loom {
    accessWidenerPath = file('src/main/resources/lumen.accesswidener')
}

tasks.named('processResources', ProcessResources) {
    from('runtime-resources') {
        exclude '**/*.pdb'
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 21
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
    withSourcesJar()
}

jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from {
        zipTree(file('libs/lumen-shaded-dependencies.jar'))
    }
}
