package dlc.lumen.api.storages.implement.helpertstorages.enumvar;

import dlc.lumen.client.modules.Module;
import java.util.List;

public class ModuleClass extends GlobalObject<Module> implements ModuleRewords {
   public static ModuleClass INSTANCE = new ModuleClass();

   public void initialize() {
      this.handleMod(
         aimBot,
         aimAssistant,
         airStuck,
         aura,
         shaderEsp,
         viralJump,
         noWeb,
         autoAccept,
         autoArmor,
         autoBrew,
         autoSwap,
         autoEat,
         autoTotem,
         packetCriticals,
         autoStan,
         autoLeave,
         nameProtect,
         autoFish,
         autoCore,
         autoZamok,
         autoMine,
         cocoaFarm,
         noInteract,
         pvpSafe,
         autoRedShulker,
         autoInvisible,
         fakePlayer,
         autoTool,
         blockOverlay,
         ambience,
         betterMinecraft,
         chestStealer,
         clientSounds,
         deathCoord,
         fastExp,
         elytraFly,
         elytraSwap,
         flight,
         freeCam,
         fullBright,
         highJump,
         interfaceModule,
         inventoryWalk,
         itemScroller,
         jumpCircle,
         lockSlot,
         noJumpDelay,
         noPush,
         noSlow,
         velocity,
         knockbackTweaks,
         particles,
         worldParticles,
         removals,
         viewArmorDurability,
         rPSpoofer,
         seeInvisibles,
         shaderHands,
         serverHelper,
         auctionHelper,
         spider,
         sprint,
         swingAnimations,
         targetESP,
         targetPearl,
         clickPearl,
         trajectories,
         triggerBot,
         viewModel,
         waterSpeed,
         noFriendDamage,
         noSlotChange,
         antiAFK,
         autoRespawn,
         zoom,
         hitboxes,
         ancientXray,
         // motionFps,
         mineHelper,
         nameTags,
         customCrosshair,
         shulkerPreview,
         healHelper,
         chunkAnimator,
         points,
         arrows,
         windHop,
         autoDodge,
         mineAssistant,
         appleFarmer,
         aucReissue,
         maceHelper,
         optimizer,
         endLooter,
         leavetracker,
         tpsSync,
         proxy,
         blockESP,
         aspectRatio
      );
   }

   private void handleMod(Module... mod) {
      this.getObject().addAll(List.of(mod));
   }
}