package dlc.lumen.api.storages.implement.helpertstorages.enumvar;

import dlc.lumen.client.modules.impl.combat.AimAssistant;
import dlc.lumen.client.modules.impl.combat.AimBot;
import dlc.lumen.client.modules.impl.combat.Aura;
import dlc.lumen.client.modules.impl.combat.AutoStan;
import dlc.lumen.client.modules.impl.combat.AutoSwap;
import dlc.lumen.client.modules.impl.combat.AutoTotem;
import dlc.lumen.client.modules.impl.combat.Hitboxes;
import dlc.lumen.client.modules.impl.combat.KnockbackTweaks;
import dlc.lumen.client.modules.impl.combat.MaceHelper;
import dlc.lumen.client.modules.impl.combat.NoFriendDamage;
import dlc.lumen.client.modules.impl.combat.PacketCriticals;
import dlc.lumen.client.modules.impl.combat.TpsSync;
import dlc.lumen.client.modules.impl.combat.TriggerBot;
import dlc.lumen.client.modules.impl.misc.AppleFarmer;
import dlc.lumen.client.modules.impl.misc.AuctionHelper;
import dlc.lumen.client.modules.impl.misc.AutoAccept;
import dlc.lumen.client.modules.impl.misc.AutoCore;
import dlc.lumen.client.modules.impl.misc.AutoLeave;
import dlc.lumen.client.modules.impl.misc.AutoMine;
import dlc.lumen.client.modules.impl.misc.AutoRedShulker;
import dlc.lumen.client.modules.impl.misc.AutoZamok;
import dlc.lumen.client.modules.impl.misc.ClientSounds;
import dlc.lumen.client.modules.impl.misc.DeathCoord;
import dlc.lumen.client.modules.impl.misc.EndLooter;
import dlc.lumen.client.modules.impl.misc.FakePlayer;
import dlc.lumen.client.modules.impl.misc.LeaveTracker;
import dlc.lumen.client.modules.impl.misc.MineAssistant;
import dlc.lumen.client.modules.impl.misc.NameProtect;
import dlc.lumen.client.modules.impl.misc.NoInteract;
import dlc.lumen.client.modules.impl.misc.Proxy;
import dlc.lumen.client.modules.impl.misc.PvpSafe;
import dlc.lumen.client.modules.impl.misc.RPSpoofer;
import dlc.lumen.client.modules.impl.misc.ServerHelper;
import dlc.lumen.client.modules.impl.movement.AirStuck;
import dlc.lumen.client.modules.impl.movement.AutoDodge;
import dlc.lumen.client.modules.impl.movement.ElytraFly;
import dlc.lumen.client.modules.impl.movement.Flight;
import dlc.lumen.client.modules.impl.movement.FreeCam;
import dlc.lumen.client.modules.impl.movement.HighJump;
import dlc.lumen.client.modules.impl.movement.InventoryWalk;
import dlc.lumen.client.modules.impl.movement.NoSlow;
import dlc.lumen.client.modules.impl.movement.NoWeb;
import dlc.lumen.client.modules.impl.movement.Spider;
import dlc.lumen.client.modules.impl.movement.Sprint;
import dlc.lumen.client.modules.impl.movement.Velocity;
import dlc.lumen.client.modules.impl.movement.WaterSpeed;
import dlc.lumen.client.modules.impl.player.AntiAFK;
import dlc.lumen.client.modules.impl.player.AucReissue;
import dlc.lumen.client.modules.impl.player.AutoArmor;
import dlc.lumen.client.modules.impl.player.AutoBrew;
import dlc.lumen.client.modules.impl.player.AutoEat;
import dlc.lumen.client.modules.impl.player.AutoFish;
import dlc.lumen.client.modules.impl.player.AutoInvisible;
import dlc.lumen.client.modules.impl.player.AutoRespawn;
import dlc.lumen.client.modules.impl.player.AutoTool;
import dlc.lumen.client.modules.impl.player.ChestStealer;
import dlc.lumen.client.modules.impl.player.ClickPearl;
import dlc.lumen.client.modules.impl.player.CocoaFarm;
import dlc.lumen.client.modules.impl.player.ElytraSwap;
import dlc.lumen.client.modules.impl.player.FastExp;
import dlc.lumen.client.modules.impl.player.ItemScroller;
import dlc.lumen.client.modules.impl.player.LockSlot;
import dlc.lumen.client.modules.impl.player.MineHelper;
import dlc.lumen.client.modules.impl.player.NoJumpDelay;
import dlc.lumen.client.modules.impl.player.NoPush;
import dlc.lumen.client.modules.impl.player.NoSlotChange;
import dlc.lumen.client.modules.impl.player.TargetPearl;
import dlc.lumen.client.modules.impl.player.WindHop;
import dlc.lumen.client.modules.impl.render.Ambience;
import dlc.lumen.client.modules.impl.render.AncientXray;
import dlc.lumen.client.modules.impl.render.Arrows;
import dlc.lumen.client.modules.impl.render.AspectRatio;
import dlc.lumen.client.modules.impl.render.BetterMinecraft;
import dlc.lumen.client.modules.impl.render.BlockOverlay;
import dlc.lumen.client.modules.impl.render.BlockESP;
import dlc.lumen.client.modules.impl.render.ChunkAnimator;
import dlc.lumen.client.modules.impl.render.CustomCrosshair;
import dlc.lumen.client.modules.impl.render.FullBright;
import dlc.lumen.client.modules.impl.render.HealHelper;
import dlc.lumen.client.modules.impl.render.Interface;
import dlc.lumen.client.modules.impl.render.JumpCircle;
import dlc.lumen.client.modules.impl.render.NameTags;
import dlc.lumen.client.modules.impl.render.Optimizer;
import dlc.lumen.client.modules.impl.render.Particles;
import dlc.lumen.client.modules.impl.render.Points;
import dlc.lumen.client.modules.impl.render.Removals;
import dlc.lumen.client.modules.impl.render.SeeInvisibles;
import dlc.lumen.client.modules.impl.render.ShaderEsp;
import dlc.lumen.client.modules.impl.render.ShaderHands;
import dlc.lumen.client.modules.impl.render.ShulkerPreview;
import dlc.lumen.client.modules.impl.render.SwingAnimations;
import dlc.lumen.client.modules.impl.render.TargetESP;
import dlc.lumen.client.modules.impl.render.Trajectories;
import dlc.lumen.client.modules.impl.render.ViewArmorDurability;
import dlc.lumen.client.modules.impl.render.ViewModel;
import dlc.lumen.client.modules.impl.render.ViralJump;
import dlc.lumen.client.modules.impl.render.WorldParticles;
import dlc.lumen.client.modules.impl.render.Zoom;

public interface ModuleRewords {
   AirStuck airStuck = AirStuck.INSTANCE;
   AimAssistant aimAssistant = AimAssistant.INSTANCE;
   Aura aura = Aura.INSTANCE;
   AutoAccept autoAccept = AutoAccept.INSTANCE;
   AutoArmor autoArmor = AutoArmor.INSTANCE;
   AutoBrew autoBrew = AutoBrew.INSTANCE;
   AutoSwap autoSwap = AutoSwap.INSTANCE;
   AutoTotem autoTotem = AutoTotem.INSTANCE;
   PacketCriticals packetCriticals = PacketCriticals.INSTANCE;
   AutoStan autoStan = AutoStan.INSTANCE;
   AutoFish autoFish = AutoFish.INSTANCE;
   AutoCore autoCore = AutoCore.INSTANCE;
   AutoZamok autoZamok = AutoZamok.INSTANCE;
   EndLooter endLooter = EndLooter.INSTANCE;
   AutoMine autoMine = AutoMine.INSTANCE;
   CocoaFarm cocoaFarm = CocoaFarm.INSTANCE;
   NoInteract noInteract = NoInteract.INSTANCE;
   Proxy proxy = Proxy.INSTANCE;
   PvpSafe pvpSafe = PvpSafe.INSTANCE;
   AutoRedShulker autoRedShulker = AutoRedShulker.INSTANCE;
   AutoInvisible autoInvisible = AutoInvisible.INSTANCE;
   DeathCoord deathCoord = DeathCoord.INSTANCE;
   LeaveTracker leavetracker = LeaveTracker.INSTANCE;
   NoWeb noWeb = NoWeb.INSTANCE;
   AutoEat autoEat = AutoEat.INSTANCE;
   ShaderEsp shaderEsp = ShaderEsp.INSTANCE;
   ViralJump viralJump = ViralJump.INSTANCE;
   AutoLeave autoLeave = AutoLeave.INSTANCE;
   NameProtect nameProtect = NameProtect.INSTANCE;
   ChestStealer chestStealer = ChestStealer.INSTANCE;
   ClientSounds clientSounds = ClientSounds.INSTANCE;
   AutoTool autoTool = AutoTool.INSTANCE;
   BlockOverlay blockOverlay = BlockOverlay.INSTANCE;
   BlockESP blockESP = BlockESP.INSTANCE;
   Ambience ambience = Ambience.INSTANCE;
   AspectRatio aspectRatio = AspectRatio.INSTANCE;
   BetterMinecraft betterMinecraft = BetterMinecraft.INSTANCE;
   ElytraFly elytraFly = ElytraFly.INSTANCE;
   ElytraSwap elytraSwap = ElytraSwap.INSTANCE;
   Flight flight = Flight.INSTANCE;
   FreeCam freeCam = FreeCam.INSTANCE;
   FullBright fullBright = FullBright.INSTANCE;
   HighJump highJump = HighJump.INSTANCE;
   Interface interfaceModule = Interface.INSTANCE;
   InventoryWalk inventoryWalk = InventoryWalk.INSTANCE;
   ItemScroller itemScroller = ItemScroller.INSTANCE;
   JumpCircle jumpCircle = JumpCircle.INSTANCE;
   LockSlot lockSlot = LockSlot.INSTANCE;
   NoJumpDelay noJumpDelay = NoJumpDelay.INSTANCE;
   NoPush noPush = NoPush.INSTANCE;
   Velocity velocity = Velocity.INSTANCE;
   KnockbackTweaks knockbackTweaks = KnockbackTweaks.INSTANCE;
   Particles particles = Particles.INSTANCE;
   WorldParticles worldParticles = WorldParticles.INSTANCE;
   FastExp fastExp = FastExp.INSTANCE;
   Removals removals = Removals.INSTANCE;
   ViewArmorDurability viewArmorDurability = ViewArmorDurability.INSTANCE;
   RPSpoofer rPSpoofer = RPSpoofer.INSTANCE;
   FakePlayer fakePlayer = FakePlayer.INSTANCE;
   SeeInvisibles seeInvisibles = SeeInvisibles.INSTANCE;
   ShaderHands shaderHands = ShaderHands.INSTANCE;
   Sprint sprint = Sprint.INSTANCE;
   SwingAnimations swingAnimations = SwingAnimations.INSTANCE;
   TargetESP targetESP = TargetESP.INSTANCE;
   TargetPearl targetPearl = TargetPearl.INSTANCE;
   ClickPearl clickPearl = ClickPearl.INSTANCE;
   TpsSync tpsSync = TpsSync.INSTANCE;
   ViewModel viewModel = ViewModel.INSTANCE;
   AimBot aimBot = AimBot.INSTANCE;
   TriggerBot triggerBot = TriggerBot.INSTANCE;
   NoSlow noSlow = NoSlow.INSTANCE;
   ServerHelper serverHelper = ServerHelper.INSTANCE;
   AuctionHelper auctionHelper = AuctionHelper.INSTANCE;
   Spider spider = Spider.INSTANCE;
   Trajectories trajectories = Trajectories.INSTANCE;
   WaterSpeed waterSpeed = WaterSpeed.INSTANCE;
   NoFriendDamage noFriendDamage = NoFriendDamage.INSTANCE;
   NoSlotChange noSlotChange = NoSlotChange.INSTANCE;
   AntiAFK antiAFK = AntiAFK.INSTANCE;
   AutoRespawn autoRespawn = AutoRespawn.INSTANCE;
   Zoom zoom = Zoom.INSTANCE;
   Hitboxes hitboxes = Hitboxes.INSTANCE;
   AncientXray ancientXray = AncientXray.INSTANCE;
   MineHelper mineHelper = MineHelper.INSTANCE;
   NameTags nameTags = NameTags.INSTANCE;
   CustomCrosshair customCrosshair = CustomCrosshair.INSTANCE;
   ShulkerPreview shulkerPreview = ShulkerPreview.INSTANCE;
   HealHelper healHelper = HealHelper.INSTANCE;
   ChunkAnimator chunkAnimator = ChunkAnimator.INSTANCE;
   Points points = Points.INSTANCE;
   Arrows arrows = Arrows.INSTANCE;
   WindHop windHop = WindHop.INSTANCE;
   AutoDodge autoDodge = AutoDodge.INSTANCE;
   MineAssistant mineAssistant = MineAssistant.INSTANCE;
   AppleFarmer appleFarmer = AppleFarmer.INSTANCE;
   AucReissue aucReissue = AucReissue.INSTANCE;
   MaceHelper maceHelper = MaceHelper.INSTANCE;
   Optimizer optimizer = Optimizer.INSTANCE;
}